### ISSUE TITLE
Create tests for Compare

### ISSUE THREAD

**Issue by BjarneRentz** [BjarneRentz/SimpleCrypto.Standard#11]
Create tests for the Method `Compare()` with the following test cases:

- Two equal strings - true
- Two different strings - false
- String a is a Substring (0,x) of string b (a: Hello, b: HelloThere) - false
- One string is null or empty - false
- Both Strings are null or empty - true (Maybe this needs some changes in the implementation)

Feel free to add more.

**Comment by CraigBanach** [comment]
Hello, I've forked your repo and am working on this issue. 👍
