### ISSUE TITLE
Add Check for Length in Compare Method and disable runtime optimization 

### ISSUE THREAD

**Issue by BjarneRentz** [BjarneRentz/SimpleCrypto.Standard#6]
Check if both strings have the same length, if not return false.

Also add the attribute `[MethodImpl(MethodImplOptions.NoOptimization)]` to restrict optimization of the code.

**Comment by nico91470** [comment]
I'm interested. Can you assigne it to me?

**Comment by BjarneRentz** [comment]
There you go!

**Comment by BjarneRentz** [comment]
Thanks for your work! I will close this issue now.
